### ISSUE TITLE
max_iter warning 

### ISSUE THREAD

**Issue by ghost** [amosschle/SGR-Tools#2]
When reducing 1000 scenarios to 3 scenarios, with split_idx=[0],, the following warning is returned by sklearn_extra.cluster.KMedoids package: 

_UserWarning: n_clusters should be larger than 2 if max_iter != 0 setting max_iter to 0._

If max_iter is defined a priori to 0 (in the KMedoids function), the reduced scenarios differ from the case where the attribute max_iter is not defined. I.e., two different sets of 3 scenarios are obtained depending on whether max_iter=0 before running the code. When setting max_iter=0 the warning disappears. 
Even though the warning specifies that max_iter is set to 0, the result changes, as the following images show:

max_iter not set to 0:
![image](https://github.com/amosschle/SGR-Tools/assets/123395390/974025bd-1964-4af1-a84a-c757ba8afc5b)

max_iter = 0: 
![image](https://github.com/amosschle/SGR-Tools/assets/123395390/dd88e323-0e92-4d9c-ad10-380fa4a9b622)

Why does this behavior exist? Could it be avoided to get always the same reduced scenarios? 

I attach the code and data to reproduce this behavior.
[scenarios.csv](https://github.com/amosschle/SGR-Tools/files/13832686/scenarios.csv)
[example_scenario_reduction.zip](https://github.com/amosschle/SGR-Tools/files/13832690/example_scenario_reduction.zip)

**Comment by amos-schledorn** [comment]
Hi @marcelsoleav, thank you for spotting this and sorry for the late response! 

I was able to reproduce the behaviour. My suspicion is that the warning is issued when reducing the final branches to one scenario. In that case, `n_cluster  = 1 < 2` and the greedy initialisation is already sufficient, so no iterations are needed (see the [scikit-learn-extra docs](https://scikit-learn-extra.readthedocs.io/en/stable/modules/cluster.html#k-medoids).

Setting `max_iter=0` might suppress the warning but it also changes the clustering process, since for the `Kmedoids` calls before the final calls (in your case only one, since you're generating scenarios for a two-stage problem), also use the greedy initial values without further iterations of `PAM`. So, this would likely lead to a worse solution.

In sum, I don't think the current behaviour is fine, although the warning is a little annoying. I have made a fix to catch this warning in `ScenarioTree._reduce_to_one_scenario`. Could you review that? (#3)
